# Generated by Django 4.2.1 on 2023-11-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='year',
            field=models.IntegerField(default=2023, max_length=50, verbose_name='Год'),
            preserve_default=False,
        ),
    ]
